### ISSUE TITLE
Radio instances should not store their own messages

### ISSUE THREAD

**Issue by axiomatic-aardvark** [graphops/graphcast-sdk#102]
**Describe the bug**
Currently if there's two Radio instances running, each of them will not only receive messages from the other one, but also their own. They will also save them in their local message store.

**To Reproduce**
This is happening both on ping pong and POI Radios.

**Expected behavior**
A Radio instance should not store it's own messages. Even more - it should not _receive_ it's own messages, this should maybe be at the Waku level.

**Comment by hopeyen** [comment]
I raised this concern in vac discord and got the response from waku team that 

> subscriptions do not take in account the origin of the messages (local or received from some peer), and also messages dont have a peerID attribute.
> you'd have to filter out the messages that you emitted

So we can only filter out the message after resolving the sender address, this can be a check `valid_sender` that returns an Error variant of `SelfMessageIgnored`. We can also take this opportunity to think about if we want to remove the local cache of attestations and find the local message during attestations?
