### ISSUE TITLE
SDK Integration tests

### ISSUE THREAD

**Issue by axiomatic-aardvark** [graphops/graphcast-sdk#48]
We should have a script (similar to the one introduced in [this PR](https://github.com/graphops/poi-radio/pull/2)) that runs integration test(s). The most critical one I can think of is to run all the crates in the examples/ folder to make sure they're running fine (so in that sense it's more of an e2e test but oh well). This will ensure no breaking changes have been introduced to the SDK and can easily be used as a health check. We can even make it mandatory for them to pass in order for a PR to be merged.

**Comment by hopeyen** [comment]
Some test scenario ideas:
- Number of expected messages: Spin up `X` number of indexers with the same allocations, expect at least `0.7X` messages for a particular block
- Correct filtering: `X` indexers have active allocations `i,j` , additional indexers A has active allocations `i` . `X` receives `i,j` messages from `X+A` , and `A` receives only `i` messages from `X` indexers
- More specific to POI-radio's Attestations:
    - sum stake: `X` indexers are normal, `Y` indexers are malicious.
        - check for the expected sum amount from the stored messages grouped by POI
        - check for the expected indexer id list
        - when `sum_stake(X)>sum_stake(Y)` For an indexer in `X`, POI is normal and there’s no conflict,
            - depending on how the test is set up, check indexer `Y` receives POI divergence error (or just another set of tests)
        - when `sum_stake(X)=sum_stake(Y)` indexers in both groups receive divergence error
    - block map: `X` indexers are normal, `Y` indexer’s block is delayed. Check that `Y`'s POI is not included in the attestation process
    - When there’s multiple topics, check that POIs are separately attested.

**Comment by axiomatic-aardvark** [comment]
All these cases should now be covered in the internal e2e repo
