### ISSUE TITLE
Boot node(s) not propagating messages

### ISSUE THREAD

**Issue by axiomatic-aardvark** [graphops/graphcast-sdk#81]
**Describe the bug**
When starting up two light nodes that are connected to the same remote boot node, they are not receiving each other's messages.

**To Reproduce**
1. Pull SDK repo
2. Set required env vars
3. Run `cargo run --example ping-pong` in two terminal windows (optional: change message content for second instance so that it's visible that messages aren't being received in the first instance's logs, also use `LOG_LEVEL=DEBUG`)

**Expected behavior**
The instances should receive each other's messages.

**Additional context**
Currently the light nodes are connecting to 1 Digitalocean droplet and 3 of our boot nodes, but it seems like none of those 4 boot node instances properly distributes messages.

**Comment by axiomatic-aardvark** [comment]
The Waku configuration was the culprit. After consulting with one of the Waku devs we tracked the issue down, see [this thread](https://discord.com/channels/864066763682218004/865466680129880074/1072935510051401850) for more context.

**Comment by axiomatic-aardvark** [comment]
The Waku configuration was the culprit. After consulting with one of the Waku devs we tracked the issue down, see [this thread](https://discord.com/channels/864066763682218004/865466680129880074/1072935510051401850) for more context.

**Comment by hopeyen** [comment]
Done:D
